#!/bin/sh /etc/rc.common

START=79

USE_PROCD=1

PATH_BIN=/bin/
PATH_UBIN=/usr/bin/
PATH_CURR=

start_instance() {
	local respawn="$1"
	local name="$2"
	local path="$3$2"
	local param="$4"

	procd_open_instance "$name"

	if [ -n "$param" ]; then
		procd_set_param command "$path" "$param"
	else
		procd_set_param command "$path"
	fi

	if [ $respawn == 1 ]; then	
		procd_set_param respawn
	fi
	if [ $respawn == 2 ]; then
		procd_set_param limits core="unlimited"
	fi
	if [ $respawn == 3 ]; then
		procd_set_param respawn
		procd_set_param limits core="unlimited"
	fi
	procd_close_instance
}

start_service() {
	echo "Start Marvell RIL depened Service Applications"

	#Set default properties
	setprop sys.service.default.loglevel 7
	
	start_instance 1 "cm" "${PATH_UBIN}"

#	start_instance 0 "applets" "${PATH_UBIN}"
	start_instance 0 "sim_service" "${PATH_UBIN}"
#	start_instance 0 "audio_if" "${PATH_CURR}"

}
