#!/bin/sh
PPP_IPPARAM="$6"

. /lib/netifd/netifd-proto.sh
proto_init_update "$IFNAME" 0
proto_send_update "$PPP_IPPARAM"
dgw=`route | grep 'default' | awk '{print $2}'`
diface=`route | grep 'default' | awk '{print $8}'`
route del -net $IPREMOTE netmask 255.255.255.255 gw $dgw dev $diface

[ -d /etc/ppp/ip-down.d ] && {
	for SCRIPT in /etc/ppp/ip-down.d/*
	do
		[ -x "$SCRIPT" ] && "$SCRIPT" "$@"
	done
}
